# Generated by Django 3.0.7 on 2020-06-20 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('level', models.CharField(choices=[('100', 100), ('200', 200), ('300', 300), ('400', 400), ('500', 500)], max_length=3)),
                ('faculty', models.CharField(choices=[('FOS', 'FOS'), ('FOE', 'FOE'), ('FBMS', 'FBMS'), ('FBSS', 'FBSS'), ('FOA', 'FOA'), ('FOL', 'FOL')], max_length=4)),
                ('department', models.CharField(choices=[('COMPUTER SCIENCE', 'COMPUTER SCIENCE'), ('MATHEMATICS', 'MATHEMATICS'), ('PHYSICS', 'PHYSICS'), ('CHEMISTRY', 'CHEMISTRY'), ('BIOLOGICAL SCIENCE', 'BIOLOGICAL SCIENCE'), ('INDUSTRIAL CHEMISTRY', 'INDUSTRIAL CHEMISTRY'), ('MICROBIOLOGY', 'MICROBIOLOGY'), ('BIOCHEMISTRY', 'BIOCHEMISTRY'), ('COMPUTER INFORMATION SYSTEM', 'COMPUTER INFORMATION SYSTEM'), ('AGRICULTURAL ENGINEERING', 'AGRICULTURAL ENGINEERING'), ('CIVIL ENGINEERING', 'CIVIL ENGINEERING'), ('ELECTRONIC & ELECTRICAL ENGINEERING', 'ELECTRONIC & ELECTRICAL ENGINEERING'), ('MECHANICAL ENGINEERING', 'MECHANICAL ENGINEERING'), ('ACCOUNTING', 'ACCOUNTING'), ('BUSINESS ADMINISTRATION', 'BUSINESS ADMINISTRATION'), ('ECONOMICS', 'ECONOMICS'), ('MASS COMMUNICATION', 'MASS COMMUNICATION'), ('POLITICAL SCIENCE', 'POLITICAL SCIENCE'), ('PUBLIC ADMINISTRATION', 'PUBLIC ADMINISTRATION'), ('LIBRARY INFORMATION SCIENCE', 'LIBRARY INFORMATION SCIENCE'), ('ANATOMY', 'ANATOMY'), ('NURSING', 'NURSING'), ('PUBLIC HEALTH', 'PUBLIC HEALTH'), ('PHYSIOLOGY', 'PHYSIOLOGY'), ('RELIGIOUS STUDIES', 'RELIGIOUS STUDIES'), ('HISTORY & INTERNATIONAL STUDIES', 'HISTORY & INTERNATIONAL STUDIES'), ('LANGUAGE & LITERARY STUDIES', 'LANGUAGE & LITERARY STUDIES')], max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RepeatingStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('100', 100), ('200', 200), ('300', 300), ('400', 400), ('500', 500)], max_length=100)),
                ('session', models.CharField(blank=True, max_length=100, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='CarryOverStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, choices=[('First', 'First'), ('Second', 'Second')], max_length=100, null=True)),
                ('session', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(blank=True, choices=[('100', 100), ('200', 200), ('300', 300), ('400', 400), ('500', 500)], max_length=10, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
